name: MaxSec CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Code Quality & Security
  quality:
    runs-on: ubuntu-latest
    name: Code Quality & Security Checks
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      
      - name: Lint with flake8
        run: |
          flake8 agent-core analyzer controller telemetry --max-line-length=120
      
      - name: Format check with black
        run: black --check agent-core analyzer controller telemetry
      
      - name: Type checking with mypy
        run: |
          mypy agent-core analyzer controller --ignore-missing-imports
      
      - name: Security scan with bandit
        run: |
          bandit -r agent-core analyzer controller -f json -o bandit-report.json
          bandit -r agent-core analyzer controller

  # Unit Tests
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11']
    name: Unit Tests (${{ matrix.os }})
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov
      
      - name: Run pytest
        run: |
          pytest tests/test_core.py -v --cov=agent-core --cov=analyzer --cov=controller --cov-report=term-missing
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests

  # Build artifacts
  build:
    runs-on: ubuntu-latest
    needs: [quality, test]
    if: success()
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install build tools
        run: |
          pip install build wheel twine
      
      - name: Build distribution
        run: |
          python -m build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-distributions
          path: dist/

  # Code analysis
  analyze:
    runs-on: ubuntu-latest
    name: Code Analysis
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Release (only on main branch)
  release:
    runs-on: ubuntu-latest
    needs: [build, analyze]
    if: github.ref == 'refs/heads/main' && success()
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: python-distributions
          path: dist/
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Notify on failure
  notify:
    runs-on: ubuntu-latest
    if: failure()
    needs: [quality, test, build]
    
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'MaxSec CI/CD Pipeline Failed'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
